name: Python Pre-Releases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11.0-beta.1 - 3.11.0']
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      mongodb:
        image: mongo:4.4.11
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}
    - shell: "bash -l {0}"
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U pip setuptools wheel codecov line_profiler
        python -m pip install bsddb3 numcodecs lmdb flake8 mypy
        python -m pip install -rrequirements_dev_minimal.txt numpy -rrequirements_dev_optional.txt pymongo redis
        python -m pip install .
        python -m pip freeze
    - shell: "bash -l {0}"
      env: 
        COVERAGE_FILE: .coverage.${{matrix.python-version}}.${{matrix.numpy_version}}
        ZARR_TEST_ABS: 0
        ZARR_TEST_MONGO: 1
        ZARR_TEST_REDIS: 1
        ZARR_V3_API_AVAILABLE: 1
      run: |
        pytest --cov=zarr --cov-config=.coveragerc --doctest-plus --cov-report xml --cov=./ --timeout=300
